package com.example.javainterview.service;

import jakarta.annotation.Nonnull;

import java.util.Collection;
import java.util.function.Consumer;

/**
 * A thread-safe batching consumer for processing words and periodically flushing
 * aggregated statistics.
 * <p>
 * This interface is designed for highly concurrent environments in which:
 * <ul>
 *   <li>Multiple producer threads invoke {@link #accept(String)} to record words.</li>
 *   <li>A separate thread invokes {@link #flush(Consumer)} to retrieve
 *       aggregated counters since the previous flush.</li>
 * </ul>
 *
 * <h2>Behavior</h2>
 * <p>
 * Implementations must collect per-word frequencies. Each invocation of
 * {@link #flush(Consumer)} must return only the counts accumulated
 * <em>since the last flush</em>. After a flush, the internal state may be cleared
 * or rotated to begin accumulating fresh statistics.
 * </p>
 *
 * <p>
 * Word ordering is not required to be preserved, and counters are returned
 * without ordering guarantees.
 * </p>
 *
 * <h2>Concurrency &amp; Thread-Safety</h2>
 * <p>
 * Implementations must be safe for concurrent use by multiple threads.
 * The {@link #accept(String)} method may be called frequently and concurrently.
 * The {@link #flush(Consumer)} method may be invoked while other threads are
 * still calling {@code accept}. Implementors may choose the concurrency strategy,
 * for example:
 * </p>
 *
 * <ul>
 *   <li>Allow concurrent accepts and flushes, or</li>
 *   <li>Block accepts during a flush while minimizing blocking duration.</li>
 * </ul>
 *
 * <p>
 * Implementations must ensure that no submitted words are lost, even if
 * {@code accept} and {@code flush} run concurrently.
 * </p>
 *
 * <h2>Performance</h2>
 * <p>
 * Implementations are expected to scale under heavy load, potentially handling
 * millions of {@code accept} calls. Minimizing lock contention and latency is
 * highly encouraged.
 * </p>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * WordBatchConsumer consumer = ...
 *
 * // Producer threads
 * consumer.accept("foo");
 * consumer.accept("bar");
 * consumer.accept("foo");
 *
 * // Flusher thread
 * consumer.flush(counters -> {
 *     for (Counter c : counters) {
 *         System.out.println(c.key() + " = " + c.count());
 *     }
 * });
 * }</pre>
 *
 * @see Counter
 */
public interface WordBatchConsumer extends Consumer<String> {

    /**
     * Records a single word to be counted in the next batch.
     * <p>
     * This method must be thread-safe. If invoked concurrently from multiple
     * threads, the implementation must ensure that the word count is aggregated
     * correctly and without loss.
     *
     * @param word the word to record; never {@code null}
     */
    @Override
    void accept(@Nonnull String word);

    /**
     * Flushes the currently accumulated per-word counts and provides the
     * results to the supplied sink.
     * <p>
     * The sink receives a collection of {@link Counter} instances representing
     * the number of times each unique word has been accepted since the last
     * flush. After flushing, the implementation may reset or replace its internal
     * data structures so that future counts start fresh.
     * </p>
     *
     * <p>
     * This method must be safe to call concurrently with {@link #accept(String)}.
     * Implementations may block new {@code accept} calls while flushing, but
     * ideally should minimize blocking time.
     * </p>
     *
     * @param sink a consumer that will receive the collection of counters
     *             generated by the flush; never {@code null}
     */
    void flush(@Nonnull Consumer<Collection<Counter>> sink);
}
